---
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates database resources.


Parameters:
  DemoProjectStage:
    Description: Demmo project environment to deploy resources.
    Type: String

  DemoProjectKMSKey:
    Type: String
    Description: Instance encryption key


Resources:
  DemoProjectTestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${DemoProjectStage}-demoprojectbucket-deploy-site
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref DemoProjectKMSKey
              SSEAlgorithm: aws:kms 
      Tags:
        - Key: Name
          Value: !Sub ${DemoProjectStage}-demoprojectbucket-deploy-site


Outputs:
  DemoProjectTestBucketOP:
    Value: !Ref DemoProjectTestBucket
    Export:
      Name: DemoProjectTestBucketOutput
